Pasma 3/front end account creation
PistolRcks/pasma pull request #50
Opened 2023-12-04 16:15 UTC by KarstenRoland

2023-12-04 16:29 UTC, doranj5121 requested changes
Please remove main.css and main.js. Thx!

2023-12-06 16:05 UTC, PistolRcks requested changes

2023-12-06 16:05 UTC, PistolRcks commented on test/client/components/AccountCreationCard.test.jsx
Since the test isn't passing, you can feel free to remove the failing tests.

2023-12-08 01:25 UTC, PistolRcks commented on test/client/components/AccountCreationCard.test.jsx
> +        expect(1).toBe(1) //! I HATE YOU JEST
lol

2023-12-08 01:25 UTC, PistolRcks approved these changes

2023-12-08 18:58 UTC, doranj5121 approved these changes
Looks very good! Impressive AccountCreationCard

2023-12-11 15:13 UTC, merged